### ISSUE TITLE
script still starts old version

### ISSUE THREAD

**Issue by malenki** [cobra/josm-update-script#5]
Some old version of the script (could be from September 4th) starts the latest version as it should be. Today I saw in the RSS feed that the script was updated so I fetched and tried it.
I did not change my josm-de.conf.
Running the latest version results in an output like this: 

Repository Root: http://josm.openstreetmap.de/svn
Build-Date: 2010-10-06 01:31:17
Last Changed Author: bastiK
Revision: 3592
Repository UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
URL: http://josm.openstreetmap.de/svn/trunk
Last Changed Date: 2010-10-05 20:34:31 +0200 (Tue, 05 Oct 2010)
Last Changed Rev: 3592

Uncaught error fetching image:
java.lang.ClassCastException: [I cannot be cast to [B
    at java.awt.image.ColorModel.getAlpha(ColorModel.java:815)
    at java.awt.image.ColorModel.getRGB(ColorModel.java:860)
    at sun.awt.image.ImageRepresentation.convertToRGB(ImageRepresentation.java:278)
    at sun.awt.image.ImageRepresentation.setPixels(ImageRepresentation.java:538)
    at java.awt.image.AreaAveragingScaleFilter.accumPixels(AreaAveragingScaleFilter.java:196)
    at java.awt.image.AreaAveragingScaleFilter.setPixels(AreaAveragingScaleFilter.java:235)
    at sun.awt.image.ImageDecoder.setPixels(ImageDecoder.java:108)
    at sun.awt.image.PNGImageDecoder.sendPixels(PNGImageDecoder.java:540)
    at sun.awt.image.PNGImageDecoder.produceImage(PNGImageDecoder.java:460)
    at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:246)
    at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:172)
    at sun.awt.image.ImageFetcher.run(ImageFetcher.java:136)
lade Plugin 'remotecontrol' (Version 22734)
lade Plugin 'undelete' (Version 22365)
lade Plugin 'openstreetbugs' (Version 22723)
RemoteControl::Accepting connections on port 8111
lade Plugin 'PicLayer' (Version 22549)
lade Plugin 'tageditor' (Version 21026)
lade Plugin 'reverter' (Version 23278)
lade Plugin 'validator' (Version 23192)
java.lang.NoClassDefFoundError: org/openstreetmap/josm/gui/bbox/SlippyMapBBoxChooser$TileSourceProvider
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at org.openstreetmap.josm.plugins.PluginInformation.loadClass(PluginInformation.java:283)
    at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:380)
    at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:440)
    at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:479)
    at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:232)
Caused by: java.lang.ClassNotFoundException: org.openstreetmap.josm.gui.bbox.SlippyMapBBoxChooser$TileSourceProvider
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    ... 7 more
drmRadeonCmdBuffer: -22. Kernel failed to parse or rejected command stream. See dmesg for more info.

**Comment by cobra** [comment]
Cannot reproduce. looks like a java/kernel/driver issue to me.

**Comment by malenki** [comment]
Switching -Dsun.java2d.opengl=true to false "solves" this issue so far.
Thanks for your attention. :)
